---
jupyter:
  jupytext:
    text_representation:
      extension: .Rmd
      format_name: rmarkdown
      format_version: '1.1'
      jupytext_version: 1.1.3
  kernelspec:
    display_name: Python 3
    language: python
    name: python3
---

# Star Wars Survey

This proyect is about analyzing star wars related surveys with a focus on cleaning and wrangling with the data

```{python}
# !ls data
```

```{python}
# Reading the star wars data
import pandas as pd
star_wars = pd.read_csv('data/star_wars.csv', encoding= 'ISO-8859-1')
```

```{python}
pd.set_option('display.max_columns', 500)
```

```{python}
# Exploratory analysis of the data
star_wars.head()
```

```{python}
# Inspecting the attributes on the relation
star_wars.columns
```

```{python}
# There is one emtpy value that has a null in the RespondentID field
# This row is removed
star_wars = star_wars[star_wars['RespondentID'].notnull()]
```

```{python}
# The'Have you seen any of the 6 films in the Star Wars franchise?' column and the 
# 'Do you consider yourself to be a fan of the Star Wars film franchise?' column are key

star_wars['Have you seen any of the 6 films in the Star Wars franchise?'].value_counts(dropna = False)
```

```{python}
star_wars['Do you consider yourself to be a fan of the Star Wars film franchise?'].value_counts(dropna = False)
```

```{python}
# The conversion of the 'Yes' and 'No' values to booleans can be made with the s.map method and a 
# dictionary

yn_dict = {
    'Yes': True,
    'No': False
}

star_wars['Do you consider yourself to be a fan of the Star Wars film franchise?'] = star_wars['Do you consider yourself to be a fan of the Star Wars film franchise?'].map(yn_dict)
star_wars['Have you seen any of the 6 films in the Star Wars franchise?'] = star_wars['Have you seen any of the 6 films in the Star Wars franchise?'].map(yn_dict)
```

```{python}
star_wars['Have you seen any of the 6 films in the Star Wars franchise?'].value_counts(dropna = False)
```

```{python}
star_wars['Do you consider yourself to be a fan of the Star Wars film franchise?'].value_counts(dropna = False)
```

```{python}
# Convering the values of columns 3 to 9 to booleans

movies = star_wars.columns[3:9]

for movie in movies:
    star_wars[movie] = star_wars[movie].notna()
    print(star_wars[movie].value_counts(dropna= False))
```

```{python}
# Renaming the seen movies related attributes
seen_movie_dict = {
    'Which of the following Star Wars films have you seen? Please select all that apply.' : 'seen_1',
    'Unnamed: 4': 'seen_2',
    'Unnamed: 5': 'seen_3',
    'Unnamed: 6': 'seen_4',
    'Unnamed: 7': 'seen_5',
    'Unnamed: 8': 'seen_6'
}

star_wars = star_wars.rename(columns = seen_movie_dict)
star_wars.head()
```

```{python}
# Converting the rating related columns to numbers

star_wars[star_wars.columns[9:15]] = star_wars[star_wars.columns[9:15]].astype(float)
```

```{python}
# Changing the name of rating related columns 

rating_names = {
    'Please rank the Star Wars films in order of preference with 1 being your favorite film in the franchise and 6 being your least favorite film.': 'ranking_1',
    'Unnamed: 10': 'ranking_2',
    'Unnamed: 11': 'ranking_3',
    'Unnamed: 12': 'ranking_4',
    'Unnamed: 13': 'ranking_5',
    'Unnamed: 14': 'ranking_6'
}

star_wars.rename(columns = rating_names, inplace = True)
star_wars.head()
```

```{python}
# Inspecting the column with the highest average ranking

star_wars[star_wars.columns[9:15]].mean()
```

```{python}
# Plotting the rankings from each movie
star_wars[star_wars.columns[9:15]].mean().sort_values().plot.bar()
```

The most liked movie seems to be the fifth one from star wars.

```{python}
# Getting the number of people that has seen each movie
star_wars[star_wars.columns[3:9]].sum().sort_values(ascending = False)
```

```{python}
# Plotting the number of people that has seen each movie

star_wars[star_wars.columns[3:9]].sum().sort_values(ascending = False).plot.bar()
```

It seems that the most seen movie is the 5th episode

```{python}
grouped_by_genre = star_wars.groupby('Gender')
```

```{python}
grouped_by_genre[star_wars.columns[3:9]].sum().plot.bar()
```

```{python}
# Analyzing differences by gender
grouped_by_genre[star_wars.columns[9:15]].mean()
```

```{python}
grouped_by_genre[star_wars.columns[9:15]].mean().plot.bar()
```

Apparently, both male and female watch more the 5th episode of Star Wars and also both liked this episode more. Females seems to dislike the 3th episode more than men. 

```{python}
# We could also analyze the data by splitting those that are fans and those that are not fans
grouped_by_fans = star_wars.groupby('Do you consider yourself to be a fan of the Star Wars film franchise?')
```

```{python}
grouped_by_fans[star_wars.columns[3:9]].sum().plot.bar()
```

```{python}
grouped_by_fans[star_wars.columns[9:15]].mean().plot.bar()
```

The most watched film by fans is the 5th and 6th episode and the mosth watched film by no fans is the 6th episode. The best rated movie is the 5th episode. There is a curious fact: Fans seems to dislike the first three episodes more than those that are no fans.

```{python}
# Analyzing data by splittin the group on those that are star trek fans and those who are not.
group_by_startreck = star_wars.groupby('Do you consider yourself to be a fan of the Star Trek franchise?')
```

```{python}
group_by_startreck[star_wars.columns[3:9]].sum().plot.bar()
```

```{python}
group_by_startreck[star_wars.columns[9:15]].sum().plot.bar()
```

There seems that the times a movie has been wathed is very similar to the graph of those that are fans of star wars. Also, the rating are pretty similar between startreck fans and those that are not fans of startreck.

```{python}
# Inspecting the data by age
grouped_by_age = star_wars.groupby('Age')
```

```{python}
watched_by_age = grouped_by_age[star_wars.columns[3:9]].sum()
watched_by_age
```

```{python}
#Checking the distribution by age
import matplotlib.pyplot as plt
fig, axes = plt.subplots(nrows=2, ncols=2)
watched_by_age.loc['18-29'].plot.bar(ax = axes[0,0])
watched_by_age.loc['30-44'].plot.bar(ax = axes[0,1])
watched_by_age.loc['45-60'].plot.bar(ax = axes[1,0])
watched_by_age.loc['> 60'].plot.bar(ax = axes[1,1])
```

```{python}
ranking_by_age = grouped_by_age[star_wars.columns[9:15]].mean()
ranking_by_age
```

```{python}
fig, axes = plt.subplots(nrows = 2, ncols = 2)
ranking_by_age.loc['18-29'].plot.bar(ax = axes[0,0])
ranking_by_age.loc['30-44'].plot.bar(ax = axes[0,1])
ranking_by_age.loc['45-60'].plot.bar(ax = axes[1,0])
ranking_by_age.loc['> 60'].plot.bar(ax = axes[1,1])
```

People between 18 and 29 have a pretty much distributed way of watching all the episodes. As age increases, people tend to watch the 5th and 6th episodes more than the others, probably because they have seen them all and just rewatch those they liked (this is consistent with the fact that the 5th and 6th episodes have the higher ratings). 

Nevertheless, older people seem to enjoy the first and second episode more than younger people, but dislike the 3th episode the most. 

```{python}

```
